---

- name: Install docker-compose
  get_url: 
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose 
    sha256sum: "{{ checksum }}"
    mode: '0755'
